### ISSUE TITLE
Question: How can i edit it to change the package name to prevent detection?

### ISSUE THREAD

**Issue by GODLIKE5** [AzozzALFiras/ALFiras#1]

**Comment by AzozzALFiras** [comment]
hello need help ?

**Comment by GODLIKE5** [comment]
Yup, how can I change the package snap to make it undetectable? If possible contact me via Instagram @godlike_5 since I'm sure if you tell me a way Snapchat will monitor and patch it. Thanks

**Comment by AzozzALFiras** [comment]
Hello I’m busy, but I will help you 
Install those and make new tweak 
And copy code from my tweak and past in your tweak new
